server:
  port: 9000

spring:
  cloud:
    gateway:
      routes:
        - id: covid-vaccination-service
          uri: http://localhost:8080/
          predicates:
            - Path=/covid-vaccination-service/vaccination/**
        - id: covid-testing-service
          uri: http://localhost:8081/
          predicates:
            - Path=/covid-testing-service/testing/**
        - id: covid-report-service
          uri: http://localhost:8083/
          predicates:
            - Path=/covid-reporting-service/reporting/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
            allowedHeaders: "*"